// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('SetContextInfoVisibility', function(visible) {
    return $("#context-info").toggle(visible);
  });

}).call(this);

//# sourceMappingURL=Panel.map
