// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('contextinfo.visible', function(visible) {
    return $("#context-info").toggle(visible);
  });

  engine.on('contextinfo.text', function(text) {
    return $("#context-info").text(text);
  });

}).call(this);

//# sourceMappingURL=Script.js.map