// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('contextinfo.visible', function(visible) {
    return $("#context-info").toggle(visible);
  });

  engine.on('contextinfo.usealt', function(use) {
    $("#context-info #norm").toggle(use);
    return $("#context-info #alt").toggle(!use);
  });

}).call(this);

//# sourceMappingURL=Script.map
