// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('SetContextInfoVisibility', function(visible) {
    return $("#context-info").toggle(visible);
  });

  engine.on('AddHtml', function(html) {
    return $("body").append(html);
  });

}).call(this);

//# sourceMappingURL=Test.map
