// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('AddPanel', function(html) {
    return $("#panels").append(html);
  });

  engine.on('RemovePanel', function(pattern) {
    return $(pattern).remove();
  });

  engine.on('AddForm', function(html) {
    return $("#forms").append(html);
  });

  engine.on('RemoveForm', function(pattern) {
    return $(pattern).remove();
  });

  engine.on('AddScript', function(src) {
    return $.getScript(src);
  });

  engine.on('AddStyle', function(src) {
    return $("<link/>", {
      rel: "stylesheet",
      type: "text/css",
      href: src
    }).appendTo("head");
  });

}).call(this);

//# sourceMappingURL=Base.map
