// Generated by CoffeeScript 1.7.1
(function() {
  engine.on('SetContextInfoVisibility', function(visible) {
    if (visible) {
      return $("#context-info").show();
    } else {
      return $("#context-info").hide();
    }
  });

}).call(this);

//# sourceMappingURL=Test.map
