// Generated by CoffeeScript 1.7.1
(function() {
  $("#escmenu").dialog({
    dialogClass: "ui-noclose",
    draggable: false,
    resizable: false,
    autoOpen: false,
    width: 200,
    height: 400,
    show: {
      effect: "fadeIn",
      duration: 300
    },
    hide: {
      effect: "fadeOut",
      duration: 300
    }
  }, $("#disconnect").button().click(function() {
    return engine.call("disconnect");
  }), $("#backtogame").button().click(function() {
    return $("#escmenu").dialog("close");
  }));

}).call(this);

//# sourceMappingURL=Script.js.map