// Generated by CoffeeScript 1.7.1
(function() {
  $("#mainmenu").dialog({
    closeOnEscape: false,
    draggable: false,
    resizable: false,
    height: 180,
    hide: {
      effect: "fadeOut",
      duration: 300
    },
    buttons: {
      "Connect": function() {
        $("#mainmenu").parent().find(":input").prop("disabled", true);
        return engine.call("connect", $("#mainmenu-form-server").val());
      },
      "Quit": function() {
        return $(this).dialog("close");
      }
    },
    close: function(event, ui) {
      return engine.call("quit");
    }
  });

  engine.on("MainMenu.Dispose", function() {
    return $("#mainmenu").dialog("destroy");
  });

}).call(this);

//# sourceMappingURL=Panel.map
