// Generated by CoffeeScript 1.7.1
(function() {
  var parent;

  parent = $("#mainmenu").parent();

  $("#mainmenu").dialog({
    dialogClass: "ui-noclose",
    closeOnEscape: false,
    draggable: false,
    resizable: false,
    width: 300,
    minHeight: "auto",
    hide: {
      effect: "fadeOut",
      duration: 300
    },
    buttons: {
      "Connect": function() {
        var dialog;
        dialog = $("#mainmenu").parent();
        $("#mainmenu-error").slideUp(200);
        dialog.find(":input").prop("disabled", true);
        dialog.find(".ui-dialog-buttonpane").slideUp(200);
        return engine.call("connect", $("#mainmenu-form-server").val());
      },
      "Quit": function() {
        return engine.call("quit");
      }
    },
    open: function() {
      return $("#mainmenu-background").show();
    },
    close: function() {
      return $("#mainmenu-background").hide();
    }
  });

  $("#mainmenu").parent().appendTo(parent);

  engine.on("MainMenu.Hide", function() {
    return $("#mainmenu").dialog("close");
  });

  engine.on("Network.ConnectFailed", function() {
    var dialog;
    $("#mainmenu-error").slideDown(200);
    dialog = $("#mainmenu").parent();
    dialog.find(":input").prop("disabled", false);
    return dialog.find(".ui-dialog-buttonpane").slideDown(200);
  });

}).call(this);

//# sourceMappingURL=Panel.map
