// Generated by CoffeeScript 1.7.1
(function() {
  var enableDialog, panel;

  panel = $("#mainmenu").parent();

  $("#mainmenu").dialog({
    dialogClass: "ui-noclose",
    closeOnEscape: false,
    draggable: false,
    resizable: false,
    width: 300,
    minHeight: "auto",
    hide: {
      effect: "fadeOut",
      duration: 300
    },
    buttons: {
      "Connect": function() {
        var dialog;
        dialog = $("#mainmenu").parent();
        $("#mainmenu-error").slideUp(200);
        dialog.find(":input").prop("disabled", true);
        dialog.find(".ui-dialog-buttonpane").slideUp(200);
        return engine.call("connect", $("#mainmenu-form-server").val(), $("#mainmenu-form-player"));
      },
      "Quit": function() {
        return engine.call("quit");
      }
    },
    open: function() {
      return $("#mainmenu-background").show();
    },
    close: function() {
      return $("#mainmenu-background").hide();
    }
  });

  $("#mainmenu").parent().appendTo(panel);

  $("#mainmenu-startserver").button().click(function() {
    return engine.call("server.start");
  });


  /* Engine Events */

  enableDialog = function() {
    var dialog;
    dialog = $("#mainmenu").parent();
    dialog.find(":input").prop("disabled", false);
    return dialog.find(".ui-dialog-buttonpane").slideDown(200);
  };

  engine.on("MainMenu.Hide", function() {
    panel.hide();
    return enableDialog();
  });

  engine.on("MainMenu.Show", function() {
    return panel.show();
  });

  engine.on("Network.ConnectFailed", function() {
    $("#mainmenu-error").slideDown(200);
    return enableDialog();
  });

}).call(this);

//# sourceMappingURL=Script.map
