// Generated by CoffeeScript 1.7.1
(function() {
  $("#teleporter").dialog({
    draggable: true,
    resizable: false,
    width: 300,
    height: 200,
    show: {
      effect: "fadeIn",
      duration: 300
    }
  });

}).call(this);

//# sourceMappingURL=Script.js.map