// Generated by CoffeeScript 1.7.1
(function() {
  var chatOutput, input;

  $("#chat").dialog({
    dialogClass: "ui-noclose",
    closeOnEscape: false,
    draggable: false,
    resizable: {
      handles: "n, e"
    },
    width: 400,
    height: 216,
    minWidth: 400,
    minHeight: 216,
    position: {
      "my": "left+6px bottom-6px",
      "at": "left bottom",
      "collision": "none"
    },
    show: {
      effect: "fadeIn",
      duration: 300
    }
  });

  $("#chat").parent().stop(true).fadeTo(200, 0.8);

  $("#chat").parent().hover((function() {
    return $(this).stop(true).fadeTo(200, 1.0);
  }), (function() {
    return $(this).stop(true).fadeTo(200, 0.8);
  }));

  $(".chat-buttons").buttonset();

  input = $("#chat-input");

  input.keyup(function(e) {
    if (e.which === 13) {
      engine.call("chat.send", input.val());
      return input.val("");
    }
  });


  /* Engine Events */

  chatOutput = $("#chat-output");

  engine.on("chat.message", function(player, message) {
    var chatLine;
    chatLine = $("<li>", {
      "class": "chat-message-prefix"
    });
    chatLine.text(player + ": " + message);
    chatOutput.append(chatLine);
    return chatOutput.scrollTop(chatOutput[0].scrollHeight);
  });

}).call(this);

//# sourceMappingURL=Script.map
