// Generated by CoffeeScript 1.7.1
(function() {
  var input;

  $("#chat").dialog({
    dialogClass: "ui-noclose",
    closeOnEscape: false,
    draggable: false,
    resizable: false,
    width: 400,
    height: "auto",
    show: {
      effect: "fadeIn",
      duration: 300
    }
  });

  $("#chat").parent().css({
    position: "fixed",
    top: "",
    left: 6,
    bottom: 6
  });

  $("#chat").parent().hover((function() {
    return $(this).stop(true).fadeTo(200, 1.0);
  }), (function() {
    return $(this).stop(true).fadeTo(200, 0.8);
  }));

  $(".chat-buttons").buttonset();

  input = $("#chat-input");

  input.keyup(function(e) {
    if (e.which === 13) {
      engine.call("chat.send", input.val());
      return input.val("");
    }
  });

}).call(this);

//# sourceMappingURL=Script.map
